Update codemagic.yaml

diff --git a/SwiftUIAllTerms/codemagic.yaml b/SwiftUIAllTerms/codemagic.yaml
--- a/SwiftUIAllTerms/codemagic.yaml
+++ b/SwiftUIAllTerms/codemagic.yaml
@@ -1,1 +1,58 @@
+workflows:
+
+
+  workflow-Basic:
+    working_directory: mobile
+    scripts:
+      - name: Build iOS
+        working_directory: mobile/ios
+        script: ...
+  Software-Type:
+    environment:
+      xcode: 14.2
+      
+      
+  workflow-Provisioning-Certificates:
+    scripts:
+      - name: Add provisioning profiles
+        script: |
+          set -e # exit on first failed command
+
+          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
+          mkdir -p "$PROFILES_HOME"
+          echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
+      - name: Add signing certificate
+        script: |
+          set -e # exit on first failed command
+
+          echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
+          keychain initialize
+          keychain add-certificates \
+              --certificate /tmp/certificate.p12 \
+              --certificate-password ${CERTIFICATE_PASSWORD?}
+      - name: Increment build number
+        script: agvtool new-version -all $BUILD_NUMBER
+      - name: Set up code signing settings on Xcode project
+        script: xcode-project use-profiles
+      - name: Build ipa for distribution
+        script: xcode-project build-ipa \
+                    --workspace "${XCODE_WORKSPACE?}" \
+                    --scheme "${XCODE_SCHEME?}"
+    artifacts:
+      - build/ios/ipa/*.ipa
+      
+      
+  workflow-Testflight:
+    publishing:
+      email:
+        recipients:
+          - yogesh.mnd@gmail.com
+          - yogesh.sharma@mobileprogramming.com
+      app_store_connect:
+        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
+        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
+        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
+        submit_to_testflight: true
+        beta_groups:
+          - Beta Testers
 
